name:                hpffp
version:             0.1.0.0
github:              "deadshot465/Hpffp"
license:             BSD3
author:              "Tetsuki Syu"
maintainer:          "tetsuki.syu1315@gmail.com"
copyright:           "2021 Tetsuki Syu"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hpffp#readme>

dependencies:
- base >= 4.7 && < 5
- text
- time

library:
  source-dirs: src

executables:
  hpffp-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hpffp

tests:
  hpffp-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hpffp
